const PLAYERS_DB = [
    // PORTIERI
    { name: "Mile Svilar", role: "P", team: "roma" },
    { name: "Marco Carnesecchi", role: "P", team: "atalanta" },
    { name: "Mike Maignan", role: "P", team: "milan" },
    { name: "Josep Martinez", role: "P", team: "inter" },
    { name: "Guglielmo Vicario", role: "P", team: "juventus" },
    { name: "Jean Butez", role: "P", team: "como" },
    { name: "Alex Meret", role: "P", team: "napoli" },
    { name: "Elia Caprile", role: "P", team: "cagliari" },
    { name: "Lukasz Skorupski", role: "P", team: "bologna" },
    { name: "David De Gea", role: "P", team: "fiorentina" },
    { name: "Wladimiro Falcone", role: "P", team: "lecce" },
    { name: "Christos Mandas", role: "P", team: "lazio" },
    { name: "Maduka Okoye", role: "P", team: "udinese" },
    { name: "Franco Perri", role: "P", team: "torino" },
    { name: "Justin Bijlow", role: "P", team: "genoa" },
    { name: "Arijanet Muric", role: "P", team: "sassuolo" },
    { name: "Filip Stankovic", role: "P", team: "venezia" },
    { name: "Davide Palmisani", role: "P", team: "frosinone" },
    { name: "Robert Sanchez", role: "P", team: "como" },
    { name: "Vanja Milinkovic-Savic", role: "P", team: "napoli" },
    { name: "Alioune Thiam", role: "P", team: "monza" },
    { name: "Edoardo Motta", role: "P", team: "lazio" },
    { name: "Manuel Daffara", role: "P", team: "parma" },
    { name: "Edoardo Corvi", role: "P", team: "parma" },
    { name: "Devis Evis Desplanches", role: "P", team: "frosinone" },
    { name: "Ivan Provedel", role: "P", team: "inter" },
    { name: "Lorenzo Montipò", role: "P", team: "venezia" },
    { name: "Marcel Mrozek", role: "P", team: "udinese" },
    { name: "Pietro Terracciano", role: "P", team: "milan" },
    { name: "Marco Bleve", role: "P", team: "lecce" },
    { name: "Alexandru Borbei", role: "P", team: "lecce" },
    { name: "Oliver Christensen", role: "P", team: "fiorentina" },
    { name: "Nikita Contini", role: "P", team: "napoli" },
    { name: "Giorgio De Marzi", role: "P", team: "roma" },
    { name: "Raffaele Di Gennaro", role: "P", team: "inter" },
    { name: "Alessio Furlanetto", role: "P", team: "lazio" },
    { name: "Filippo Ghidotti", role: "P", team: "parma" },
    { name: "Pierluigi Gollini", role: "P", team: "roma" },
    { name: "Kamil Grabara", role: "P", team: "juventus" },
    { name: "Massimo Grandi", role: "P", team: "venezia" },
    { name: "Eetu Happonen", role: "P", team: "bologna" },
    { name: "Daniel Israel", role: "P", team: "torino" },
    { name: "Nicolas Lezzerini", role: "P", team: "fiorentina" },
    { name: "Luka Lolic", role: "P", team: "frosinone" },
    { name: "Igor Mascardi", role: "P", team: "torino" },
    { name: "Daniele Padelli", role: "P", team: "udinese" },
    { name: "Penev", role: "P", team: "lecce" },
    { name: "Maurizio Pessina", role: "P", team: "bologna" },
    { name: "Piana", role: "P", team: "udinese" },
    { name: "Carlo Pinsoglio", role: "P", team: "juventus" },
    { name: "Matteo Pisseri", role: "P", team: "frosinone" },
    { name: "Pompei", role: "P", team: "atalanta" },
    { name: "Pozzi", role: "P", team: "venezia" },
    { name: "Boris Radunovic", role: "P", team: "cagliari" },
    { name: "Renzetti", role: "P", team: "lazio" },
    { name: "Francesco Rossi", role: "P", team: "atalanta" },
    { name: "Antonino Russo", role: "P", team: "sassuolo" },
    { name: "Giacomo Satalino", role: "P", team: "sassuolo" },
    { name: "Alen Sherri", role: "P", team: "cagliari" },
    { name: "Siviero", role: "P", team: "torino" },
    { name: "Daniele Sommariva", role: "P", team: "genoa" },
    { name: "Marco Sportiello", role: "P", team: "atalanta" },
    { name: "Stolz", role: "P", team: "genoa" },
    { name: "Strajnar", role: "P", team: "monza" },
    { name: "Tornqvist", role: "P", team: "monza" },
    { name: "Lorenzo Torriani", role: "P", team: "milan" },
    { name: "Stefano Turati", role: "P", team: "sassuolo" },
    { name: "Devis Vasquez", role: "P", team: "roma" },
    { name: "Pietro Vigorito", role: "P", team: "como" },

    // DIFENSORI
    { name: "Gleison Bremer", role: "D", team: "juventus" },
    { name: "Nahuel Molina", role: "D", team: "roma" },
    { name: "Wesley", role: "D", team: "roma" },
    { name: "Federico Dimarco", role: "D", team: "inter" },
    { name: "Manuel Akanji", role: "D", team: "inter" },
    { name: "Alessandro Bastoni", role: "D", team: "inter" },
    { name: "Yann Bisseck", role: "D", team: "inter" },
    { name: "Gianluca Mancini", role: "D", team: "roma" },
    { name: "Giovanni Di Lorenzo", role: "D", team: "napoli" },
    { name: "Strahinja Pavlovic", role: "D", team: "milan" },
    { name: "Amir Rrahmani", role: "D", team: "napoli" },
    { name: "Pierre Kalulu", role: "D", team: "juventus" },
    { name: "Evan Ndicka", role: "D", team: "roma" },
    { name: "Oumar Solet", role: "D", team: "udinese" },
    { name: "Mario Hermoso", role: "D", team: "roma" },
    { name: "Andy Diouf", role: "D", team: "inter" },
    { name: "Giorgio Scalvini", role: "D", team: "atalanta" },
    { name: "John Stones", role: "D", team: "inter" },
    { name: "Mario Gila", role: "D", team: "milan" },
    { name: "Ramon", role: "D", team: "como" },
    { name: "Leo Ostigard", role: "D", team: "genoa" },
    { name: "Trevoh Chalobah", role: "D", team: "como" },
    { name: "Danilho Doekhi", role: "D", team: "lazio" },
    { name: "Juan Miranda", role: "D", team: "bologna" },
    { name: "Hassane Kamara", role: "D", team: "udinese" },
    { name: "Emanuele Valeri", role: "D", team: "parma" },
    { name: "Alex Valle", role: "D", team: "como" },
    { name: "Johan Vasquez", role: "D", team: "genoa" },
    { name: "Davide Bartesaghi", role: "D", team: "milan" },
    { name: "Pietro Comuzzo", role: "D", team: "torino" },
    { name: "Diego Carlos", role: "D", team: "parma" },
    { name: "Matteo Gabbia", role: "D", team: "milan" },
    { name: "Isak Hien", role: "D", team: "atalanta" },
    { name: "Oliver Kempf", role: "D", team: "como" },
    { name: "Tiago Gabriel", role: "D", team: "lecce" },
    { name: "Gabriele Bracaglia", role: "D", team: "frosinone" },
    { name: "Alessandro Buongiorno", role: "D", team: "napoli" },
    { name: "Saul Coco", role: "D", team: "torino" },
    { name: "Yan Couto", role: "D", team: "como" },
    { name: "Enrico Delprato", role: "D", team: "parma" },
    { name: "Josh Doig", role: "D", team: "sassuolo" },
    { name: "Radu Dragusin", role: "D", team: "fiorentina" },
    { name: "Jimenez", role: "D", team: "fiorentina" },
    { name: "Leonardo Spinazzola", role: "C", team: "napoli" },
    { name: "Jhon Lucumi", role: "D", team: "juventus" },
    { name: "Zeki Celik", role: "D", team: "juventus" },
    { name: "Emil Holm", role: "D", team: "bologna" },
    { name: "Ardian Ismajli", role: "D", team: "torino" },
    { name: "Konstantinos Koulierakis", role: "D", team: "roma" },
    { name: "Fedde Leysen", role: "D", team: "sassuolo" },
    { name: "Adam Marusic", role: "D", team: "lazio" },
    { name: "Yerry Mina", role: "D", team: "cagliari" },
    { name: "Nuno Tavares", role: "D", team: "lazio" },
    { name: "Arthur Theate", role: "D", team: "bologna" },
    { name: "Mergim Vojvoda", role: "D", team: "udinese" },
    { name: "Benoit Badiashile", role: "D", team: "napoli" },
    { name: "Antonino Gallo", role: "D", team: "lecce" },
    { name: "Thomas Kristensen", role: "D", team: "atalanta" },
    { name: "Federico Gatti", role: "D", team: "juventus" },
    { name: "Sondre Heggem", role: "D", team: "bologna" },
    { name: "Jay Idzes", role: "D", team: "sassuolo" },
    { name: "Giovanni Marcandalli", role: "D", team: "genoa" },
    { name: "Adam Obert", role: "D", team: "cagliari" },
    { name: "Rafael Obrador", role: "D", team: "sassuolo" },
    { name: "Benjamin Pavard", role: "D", team: "inter" },
    { name: "Alfonso Pedraza", role: "D", team: "lazio" },
    { name: "Fikayo Tomori", role: "D", team: "milan" },
    { name: "Valdepenas", role: "D", team: "fiorentina" },
    { name: "Leonardo Balerdi", role: "D", team: "roma" },
    { name: "Beidi", role: "D", team: "cagliari" },
    { name: "Armel Bella-Kotchap", role: "D", team: "venezia" },
    { name: "Sam Beukema", role: "D", team: "napoli" },
    { name: "Correia", role: "D", team: "venezia" },
    { name: "Koni De Winter", role: "D", team: "milan" },
    { name: "Andrea Cambiaso", role: "D", team: "juventus" },
    { name: "Daniele Ghilardi", role: "D", team: "roma" },
    { name: "Christian Kabasele", role: "D", team: "udinese" },
    { name: "Lloyd Kelly", role: "D", team: "juventus" },
    { name: "Odilon Kossounou", role: "D", team: "atalanta" },
    { name: "Gabriele Monterisi", role: "D", team: "frosinone" },
    { name: "Devyne Rensch", role: "D", team: "roma" },
    { name: "Josip Sutalo", role: "D", team: "lazio" },
    { name: "Renato Veiga", role: "D", team: "lecce" },
    { name: "Viery", role: "D", team: "fiorentina" },
    { name: "Dodo", role: "D", team: "fiorentina" },
    { name: "Sebastian Walukiewicz", role: "D", team: "sassuolo" },
    { name: "Ze Pedro", role: "D", team: "cagliari" },
    { name: "Carlos Augusto", role: "D", team: "inter" },
    { name: "Belghali", role: "D", team: "torino" },
    { name: "Britschgi", role: "D", team: "parma" },
    { name: "Andrea Carboni", role: "D", team: "monza" },
    { name: "Romano Floriani Mussolini", role: "D", team: "lazio" },
    { name: "Eray Comert", role: "D", team: "torino" },
    { name: "Kialonda Gaspar", role: "D", team: "lecce" },
    { name: "Thibaut Hainaut", role: "D", team: "venezia" },
    { name: "Kaiki", role: "D", team: "como" },
    { name: "Kofler", role: "D", team: "cagliari" },
    { name: "Sead Kolasinac", role: "D", team: "atalanta" },
    { name: "Casper Odenthal", role: "D", team: "sassuolo" },
    { name: "Marin Pongracic", role: "D", team: "fiorentina" },
    { name: "Oliver Provstgaard", role: "D", team: "lazio" },
    { name: "Luca Ranieri", role: "D", team: "fiorentina" },
    { name: "Mangas", role: "D", team: "monza" },
    { name: "Hrvoje Smolcic", role: "D", team: "como" },
    { name: "Lautaro Valenti", role: "D", team: "parma" },
    { name: "Martin Vitik", role: "D", team: "bologna" },
    { name: "Nicolò Bertola", role: "D", team: "udinese" },
    { name: "Duje Caleta-Car", role: "D", team: "sassuolo" },
    { name: "Gabriele Calvani", role: "D", team: "frosinone" },
    { name: "Raoul Bellanova", role: "D", team: "atalanta" },
    { name: "Jesus", role: "D", team: "venezia" },
    { name: "Bernasconi", role: "D", team: "atalanta" },
    { name: "Joao Mario", role: "D", team: "fiorentina" },
    { name: "Moreno", role: "D", team: "venezia" },
    { name: "Rodriguez", role: "D", team: "cagliari" },
    { name: "Jamil Siebert", role: "D", team: "lecce" },
    { name: "Fortini", role: "D", team: "torino" },
    { name: "Enzo Tchato", role: "D", team: "frosinone" },
    { name: "Alhassane", role: "D", team: "bologna" },
    { name: "Fali Cande", role: "D", team: "sassuolo" },
    { name: "Giorgio Cittadini", role: "D", team: "frosinone" },
    { name: "Alberto Dossena", role: "D", team: "como" },
    { name: "Enzo Ebosse", role: "D", team: "udinese" },
    { name: "Pervis Estupinan", role: "D", team: "milan" },
    { name: "Helland", role: "D", team: "bologna" },
    { name: "Willy Kambwala", role: "D", team: "como" },
    { name: "Manuel Lazzari", role: "D", team: "lazio" },
    { name: "Giorgio Lucchesi", role: "D", team: "monza" },
    { name: "Mario Mitaj", role: "D", team: "genoa" },
    { name: "Anthony Oyono", role: "D", team: "frosinone" },
    { name: "Luca Pellegrini", role: "D", team: "lazio" },
    { name: "Schingtienne", role: "D", team: "venezia" },
    { name: "Troilo", role: "D", team: "parma" },
    { name: "Nicolò Casale", role: "D", team: "bologna" },
    { name: "Cinquegrano", role: "D", team: "sassuolo" },
    { name: "Bartol Franjic", role: "D", team: "venezia" },
    { name: "Saba Goglichidze", role: "D", team: "monza" },
    { name: "Halhal", role: "D", team: "venezia" },
    { name: "Kouadio", role: "D", team: "monza" },
    { name: "Patterson", role: "D", team: "torino" },
    { name: "Marianucci", role: "D", team: "napoli" },
    { name: "Rafa Marin", role: "D", team: "napoli" },
    { name: "Ridgeciano Haps", role: "D", team: "venezia" },
    { name: "Samuele Birindelli", role: "D", team: "monza" },
    { name: "Ndiaye", role: "D", team: "parma" },
    { name: "Palma", role: "D", team: "udinese" },
    { name: "Patric", role: "D", team: "lazio" },
    { name: "Puczka", role: "D", team: "genoa" },
    { name: "Marin Sverko", role: "D", team: "venezia" },
    { name: "Alexa Terzic", role: "D", team: "frosinone" },
    { name: "Ignace Van der Brempt", role: "D", team: "sassuolo" },
    { name: "James Abankwah", role: "D", team: "udinese" },
    { name: "Kevin Akpoguma", role: "D", team: "frosinone" },
    { name: "Diawara", role: "D", team: "milan" },
    { name: "Samuel Gigot", role: "D", team: "lazio" },
    { name: "Edoardo Goldaniga", role: "D", team: "como" },
    { name: "Gaby Jean", role: "D", team: "lecce" },
    { name: "Mathias Olivera", role: "D", team: "napoli" },
    { name: "Otoa", role: "D", team: "genoa" },
    { name: "Valentin Antov", role: "D", team: "monza" },
    { name: "Franco Carboni", role: "D", team: "parma" },
    { name: "Lorenzo De Silvestri", role: "D", team: "bologna" },
    { name: "Drobnic", role: "D", team: "parma" },
    { name: "Maye", role: "D", team: "monza" },
    { name: "Corrie Ndaba", role: "D", team: "lecce" },
    { name: "Marco Pieragnolo", role: "D", team: "sassuolo" },
    { name: "Daniele Rugani", role: "D", team: "juventus" },
    { name: "Filippo Terracciano", role: "D", team: "milan" },
    { name: "Addo", role: "D", team: "lecce" },
    { name: "Wisdom Amey", role: "D", team: "frosinone" },
    { name: "Omar Fayed", role: "D", team: "frosinone" },
    { name: "Gomes", role: "D", team: "venezia" },
    { name: "Paz", role: "D", team: "sassuolo" },
    { name: "Ziolkowski", role: "D", team: "monza" },

    // CENTROCAMPISTI
    { name: "Nico Paz", role: "C", team: "como" },
    { name: "Hakan Calhanoglu", role: "C", team: "inter" },
    { name: "Scott McTominay", role: "C", team: "napoli" },
    { name: "Christian Pulisic", role: "C", team: "milan" },
    { name: "Riccardo Orsolini", role: "C", team: "bologna" },
    { name: "Martin Baturina", role: "C", team: "como" },
    { name: "Adrien Rabiot", role: "C", team: "milan" },
    { name: "Mattia Zaccagni", role: "C", team: "lazio" },
    { name: "Nicolò Zaniolo", role: "C", team: "udinese" },
    { name: "Kevin De Bruyne", role: "C", team: "napoli" },
    { name: "Nicolò Barella", role: "C", team: "inter" },
    { name: "Lucas Da Cunha", role: "C", team: "como" },
    { name: "Nikola Vlasic", role: "C", team: "torino" },
    { name: "Albert Gudmundsson", role: "C", team: "lazio" },
    { name: "Mora Carvalho", role: "C", team: "roma" },
    { name: "Ederson", role: "C", team: "atalanta" },
    { name: "Weston McKennie", role: "C", team: "juventus" },
    { name: "Atta", role: "C", team: "fiorentina" },
    { name: "Francisco Conceicao", role: "C", team: "juventus" },
    { name: "Franco Mastantuono", role: "C", team: "fiorentina" },
    { name: "Alajbegovic", role: "C", team: "juventus" },
    { name: "Luka Modric", role: "C", team: "milan" },
    { name: "Lazar Samardzic", role: "C", team: "atalanta" },
    { name: "Piotr Zielinski", role: "C", team: "inter" },
    { name: "Pedro Goncalves", role: "C", team: "fiorentina" },
    { name: "Manu Kone", role: "C", team: "roma" },
    { name: "Kenneth Taylor", role: "C", team: "lazio" },
    { name: "Davide Frattesi", role: "C", team: "lazio" },
    { name: "Lorenzo Pellegrini", role: "C", team: "roma" },
    { name: "Frank Anguissa", role: "C", team: "napoli" },
    { name: "Da Silva Moreira", role: "C", team: "milan" },
    { name: "Jurgen Ekkelenkamp", role: "C", team: "udinese" },
    { name: "Curtis Jones", role: "C", team: "inter" },
    { name: "Rolando Mandragora", role: "C", team: "torino" },
    { name: "Maximo Perrone", role: "C", team: "como" },
    { name: "Alexis Saelemaekers", role: "C", team: "milan" },
    { name: "Rodriguez", role: "C", team: "como" },
    { name: "Jon Rowe", role: "C", team: "atalanta" },
    { name: "Matteo Politano", role: "C", team: "napoli" },
    { name: "Tommaso Baldanzi", role: "C", team: "genoa" },
    { name: "Djed Spence", role: "C", team: "inter" },
    { name: "Gustav Isaksen", role: "C", team: "lazio" },
    { name: "Jens Odgaard", role: "C", team: "bologna" },
    { name: "Luka Sucic", role: "C", team: "inter" },
    { name: "Kristian Thorstvedt", role: "C", team: "sassuolo" },
    { name: "Khéphren Thuram", role: "C", team: "juventus" },
    { name: "Cesare Casadei", role: "C", team: "torino" },
    { name: "Omari Hutchinson", role: "C", team: "milan" },
    { name: "Franck Kessie", role: "C", team: "atalanta" },
    { name: "Mario Pasalic", role: "C", team: "atalanta" },
    { name: "Andrea Colpani", role: "C", team: "monza" },
    { name: "Bryan Cristante", role: "C", team: "roma" },
    { name: "Eljif Elmas", role: "C", team: "atalanta" },
    { name: "Nicolò Fagioli", role: "C", team: "fiorentina" },
    { name: "Lewis Ferguson", role: "C", team: "bologna" },
    { name: "Jesper Karlstrom", role: "C", team: "udinese" },
    { name: "Stanislav Lobotka", role: "C", team: "napoli" },
    { name: "Manuel Locatelli", role: "C", team: "juventus" },
    { name: "Antonio Vergara", role: "C", team: "napoli" },
    { name: "Cristian Volpato", role: "C", team: "sassuolo" },
    { name: "Adrian Bernabé", role: "C", team: "parma" },
    { name: "Giacomo Calò", role: "C", team: "frosinone" },
    { name: "Samuel Chukwueze", role: "C", team: "milan" },
    { name: "Romano Schmid", role: "C", team: "frosinone" },
    { name: "Djibril Sow", role: "C", team: "genoa" },
    { name: "Maxence Caqueret", role: "C", team: "como" },
    { name: "Gianluca Gaetano", role: "C", team: "atalanta" },
    { name: "Kone", role: "C", team: "sassuolo" },
    { name: "Teun Koopmeiners", role: "C", team: "juventus" },
    { name: "Niccolò Pisilli", role: "C", team: "roma" },
    { name: "Unai Gomez", role: "C", team: "udinese" },
    { name: "Nicola Zalewski", role: "C", team: "atalanta" },
    { name: "Davide Zappacosta", role: "C", team: "atalanta" },
    { name: "Nicolò Cambiaghi", role: "C", team: "bologna" },
    { name: "Matteo Cancellieri", role: "C", team: "lazio" },
    { name: "Michel Adopo", role: "C", team: "cagliari" },
    { name: "Tanner Busio", role: "C", team: "venezia" },
    { name: "Jacopo Fazzini", role: "C", team: "cagliari" },
    { name: "Morten Frendrup", role: "C", team: "genoa" },
    { name: "Cher Ndour", role: "C", team: "fiorentina" },
    { name: "Jakub Piotrowski", role: "C", team: "udinese" },
    { name: "Vasilije Adzic", role: "C", team: "sassuolo" },
    { name: "Nemanja Matic", role: "C", team: "sassuolo" },
    { name: "Henrikh Mkhitaryan", role: "C", team: "inter" },
    { name: "Matteo Pessina", role: "C", team: "monza" },
    { name: "Tommaso Pobega", role: "C", team: "bologna" },
    { name: "Sarr", role: "C", team: "juventus" },
    { name: "Harry Winks", role: "C", team: "cagliari" },
    { name: "Edon Zhegrova", role: "C", team: "juventus" },
    { name: "Toma Basic", role: "C", team: "venezia" },
    { name: "Braganca", role: "C", team: "torino" },
    { name: "Mamadou Coulibaly", role: "C", team: "lecce" },
    { name: "Marten De Roon", role: "C", team: "roma" },
    { name: "Mikael Ellertsson", role: "C", team: "genoa" },
    { name: "Ardon Jashari", role: "C", team: "milan" },
    { name: "Keita", role: "C", team: "parma" },
    { name: "Mattia Liberali", role: "C", team: "como" },
    { name: "Milla", role: "C", team: "como" },
    { name: "Oulai", role: "C", team: "fiorentina" },
    { name: "Perez", role: "C", team: "venezia" },
    { name: "Romano", role: "C", team: "cagliari" },
    { name: "Nicolò Rovella", role: "C", team: "lazio" },
    { name: "Ebenezer Akinsanmiro", role: "C", team: "monza" },
    { name: "Cacciamani", role: "C", team: "torino" },
    { name: "Fisayo Dele-Bashiru", role: "C", team: "lazio" },
    { name: "Mattia Felici", role: "C", team: "cagliari" },
    { name: "Omri Gandelman", role: "C", team: "lecce" },
    { name: "Gvidas Gineitis", role: "C", team: "torino" },
    { name: "Ruben Loftus-Cheek", role: "C", team: "milan" },
    { name: "Luis Henrique", role: "C", team: "inter" },
    { name: "Nikola Moro", role: "C", team: "bologna" },
    { name: "Hans Nicolussi Caviglia", role: "C", team: "parma" },
    { name: "Traore", role: "C", team: "genoa" },
    { name: "Alessio Zerbin", role: "C", team: "frosinone" },
    { name: "Nadir Zortea", role: "C", team: "bologna" },
    { name: "Amorim", role: "C", team: "genoa" },
    { name: "Bakola", role: "C", team: "sassuolo" },
    { name: "Medon Berisha", role: "C", team: "lecce" },
    { name: "Federico Bernardeschi", role: "C", team: "bologna" },
    { name: "Marco Brescianini", role: "C", team: "fiorentina" },
    { name: "Nicolas Gonzalez", role: "C", team: "juventus" },
    { name: "Danilo Cataldi", role: "C", team: "lazio" },
    { name: "Douglas Luiz", role: "C", team: "juventus" },
    { name: "Giovanni Fabbian", role: "C", team: "parma" },
    { name: "Alieu Fadera", role: "C", team: "cagliari" },
    { name: "Favasuli", role: "C", team: "napoli" },
    { name: "Kian Fitz-Jim", role: "C", team: "torino" },
    { name: "Florian Grillitsch", role: "C", team: "frosinone" },
    { name: "Emirhan Ilkhan", role: "C", team: "torino" },
    { name: "Meichtry", role: "C", team: "genoa" },
    { name: "Simon Sohm", role: "C", team: "venezia" },
    { name: "Yukinari Sugawara", role: "C", team: "cagliari" },
    { name: "Idrissa Touré", role: "C", team: "monza" },
    { name: "Amondarain", role: "C", team: "bologna" },
    { name: "Warren Bondo", role: "C", team: "milan" },
    { name: "Cichella", role: "C", team: "frosinone" },
    { name: "Michael Folorunsho", role: "C", team: "monza" },
    { name: "Billy Gilmour", role: "C", team: "napoli" },
    { name: "Masini", role: "C", team: "frosinone" },
    { name: "Junior Messias", role: "C", team: "genoa" },
    { name: "Miller", role: "C", team: "udinese" },
    { name: "Ngom", role: "C", team: "lecce" },
    { name: "Fabiano Parisi", role: "C", team: "fiorentina" },
    { name: "Samuele Ricci", role: "C", team: "como" },
    { name: "Sagrado", role: "C", team: "venezia" },
    { name: "Ibrahim Sulemana", role: "C", team: "sassuolo" },
    { name: "Patrick Ciurria", role: "C", team: "monza" },
    { name: "Lorenzo Colombo", role: "C", team: "monza" },
    { name: "Alessandro Deiola", role: "C", team: "cagliari" },
    { name: "Kingsley Ehizibue", role: "C", team: "genoa" },
    { name: "Stephan El Shaarawy", role: "C", team: "genoa" },
    { name: "Gaetano Oristanio", role: "C", team: "torino" },
    { name: "Roberto Gagliardini", role: "C", team: "cagliari" },
    { name: "Francesco Gelli", role: "C", team: "frosinone" },
    { name: "Sandi Lovric", role: "C", team: "udinese" },
    { name: "Youssef Maleh", role: "C", team: "lecce" },
    { name: "Luca Mazzitelli", role: "C", team: "como" },
    { name: "Yunus Musah", role: "C", team: "milan" },
    { name: "Ordonez", role: "C", team: "parma" },
    { name: "Rodriguez", role: "C", team: "torino" },
    { name: "Vincent Sierro", role: "C", team: "parma" },
    { name: "Aleksandar Stankovic", role: "C", team: "inter" },
    { name: "Venturino", role: "C", team: "genoa" },
    { name: "Arizala", role: "C", team: "udinese" },
    { name: "Christian Comotto", role: "C", team: "milan" },
    { name: "Drameh", role: "C", team: "genoa" },
    { name: "Alfred Duncan", role: "C", team: "venezia" },
    { name: "Gorter", role: "C", team: "lecce" },
    { name: "Luis Hasa", role: "C", team: "frosinone" },
    { name: "Thorir Helgason", role: "C", team: "venezia" },
    { name: "Luca Lipani", role: "C", team: "sassuolo" },
    { name: "Anass Salah-Eddine", role: "C", team: "roma" },
    { name: "Gabriele Zanoli", role: "C", team: "udinese" },
    { name: "Aurelio", role: "C", team: "cagliari" },
    { name: "Reda Belahyane", role: "C", team: "lazio" },
    { name: "Cristiano Biraghi", role: "C", team: "torino" },
    { name: "Daniel Boloca", role: "C", team: "sassuolo" },
    { name: "Juan Cabal", role: "C", team: "juventus" },
    { name: "Giorgi Chakvetadze", role: "C", team: "udinese" },
    { name: "Oussama El Azzouzi", role: "C", team: "bologna" },
    { name: "Amario Cozier-Duberry", role: "C", team: "monza" },
    { name: "Idrissi", role: "C", team: "cagliari" },
    { name: "Lukas Ilic", role: "C", team: "lecce" },
    { name: "Massolin", role: "C", team: "cagliari" },
    { name: "Stefano Sabelli", role: "C", team: "genoa" },
    { name: "Oier Zarraga", role: "C", team: "udinese" },
    { name: "Samuel Mbangula", role: "C", team: "bologna" },
    { name: "Bakoune", role: "C", team: "monza" },
    { name: "Riccardo Ciervo", role: "C", team: "cagliari" },
    { name: "Benjamin Cremaschi", role: "C", team: "parma" },
    { name: "Foe Ondoa", role: "C", team: "monza" },
    { name: "Andrea Ghion", role: "C", team: "sassuolo" },
    { name: "Kone", role: "C", team: "frosinone" },
    { name: "Lulli", role: "C", team: "roma" },
    { name: "Pasquale Mazzocchi", role: "C", team: "venezia" },
    { name: "Mitchell Bakker", role: "C", team: "atalanta" },
    { name: "Dembele", role: "C", team: "lecce" },
    { name: "Youssouf Fofana", role: "C", team: "lecce" },
    { name: "Mohamed Kaba", role: "C", team: "lecce" },
    { name: "Luongo", role: "C", team: "torino" },
    { name: "Mout", role: "C", team: "monza" },
    { name: "Akarakiri", role: "C", team: "cagliari" },
    { name: "Dagasso", role: "C", team: "venezia" },
    { name: "El Azzouzi", role: "C", team: "frosinone" },
    { name: "Farcomeni", role: "C", team: "lazio" },
    { name: "Galassi", role: "C", team: "lazio" },
    { name: "Konate", role: "C", team: "parma" },
    { name: "Kovac", role: "C", team: "lecce" },
    { name: "Lahdo", role: "C", team: "como" },
    { name: "Liteta", role: "C", team: "cagliari" },
    { name: "Przyborek", role: "C", team: "lazio" },
    { name: "Wiafe", role: "C", team: "genoa" },
    { name: "Dabo", role: "C", team: "venezia" },
    

    // ATTACCANTI
    { name: "Donyell Malen", role: "A", team: "roma" },
    { name: "Lautaro Martinez", role: "A", team: "inter" },
    { name: "Rasmus Hojlund", role: "A", team: "napoli" },
    { name: "Marcus Thuram", role: "A", team: "inter" },
    { name: "Goncalo Ramos", role: "A", team: "milan" },
    { name: "Nick Woltemade", role: "A", team: "juventus" },
    { name: "Randal Kolo Muani", role: "A", team: "juventus" },
    { name: "Moise Kean", role: "A", team: "como" },
    { name: "Anastasios Douvikas", role: "A", team: "como" },
    { name: "Kenan Yildiz", role: "A", team: "juventus" },
    { name: "Keinan Davis", role: "A", team: "udinese" },
    { name: "Gianluca Scamacca", role: "A", team: "atalanta" },
    { name: "Domenico Berardi", role: "A", team: "sassuolo" },
    { name: "Paulo Dybala", role: "A", team: "roma" },
    { name: "Nikola Krstovic", role: "A", team: "atalanta" },
    { name: "Francesco Pio Esposito", role: "A", team: "inter" },
    { name: "Giovanni Simeone", role: "A", team: "torino" },
    { name: "Matias Soulé", role: "A", team: "roma" },
    { name: "Santiago Castro", role: "A", team: "roma" },
    { name: "Charles De Ketelaere", role: "A", team: "atalanta" },
    { name: "Armand Laurienté", role: "A", team: "sassuolo" },
    { name: "Assane Diao", role: "A", team: "como" },
    { name: "Artem Dovbyk", role: "A", team: "bologna" },
    { name: "Andrea Pinamonti", role: "A", team: "lazio" },
    { name: "Giacomo Raspadori", role: "A", team: "atalanta" },
    { name: "Beto", role: "A", team: "fiorentina" },
    { name: "Lorenzo Colombo", role: "A", team: "genoa" },
    { name: "Salvatore Esposito", role: "A", team: "sassuolo" },
    { name: "Antonio Raimondo", role: "A", team: "frosinone" },
    { name: "Che Adams", role: "A", team: "torino" },
    { name: "John Yeboah", role: "A", team: "venezia" },
    { name: "Roberto Piccoli", role: "A", team: "bologna" },
    { name: "Kev Bowie", role: "A", team: "sassuolo" },
    { name: "Pellegrino", role: "A", team: "fiorentina" },
    { name: "Vitinha", role: "A", team: "genoa" },
    { name: "Ange-Yoan Bonny", role: "A", team: "inter" },
    { name: "Patrick Cutrone", role: "A", team: "monza" },
    { name: "Santos", role: "A", team: "napoli" },
    { name: "Nikola Stulic", role: "A", team: "lecce" },
    { name: "Duvan Zapata", role: "A", team: "torino" },
    { name: "Adams", role: "A", team: "venezia" },
    { name: "Ghedjemis", role: "A", team: "frosinone" },
    { name: "Kevin Carlos", role: "A", team: "cagliari" },
    { name: "Jeremie Boga", role: "A", team: "juventus" },
    { name: "Kvernadze", role: "A", team: "frosinone" },
    { name: "Daniel Maldini", role: "A", team: "cagliari" },
    { name: "David Neres", role: "A", team: "napoli" },
    { name: "Luka Romero", role: "A", team: "parma" },
    { name: "Bobcek", role: "A", team: "frosinone" },
    { name: "Willem Geubbels", role: "A", team: "lecce" },
    { name: "Tijjani Noslin", role: "A", team: "lazio" },
    { name: "Santiago Pierotti", role: "A", team: "lecce" },
    { name: "Milutin Osmajic", role: "A", team: "genoa" },
    { name: "Robinson", role: "A", team: "monza" },
    { name: "Albion Rrahmani", role: "A", team: "venezia" },
    { name: "Ibrahim Sulemana", role: "A", team: "atalanta" },
    { name: "Addai", role: "A", team: "como" },
    { name: "Wilfried Gnonto", role: "A", team: "fiorentina" },
    { name: "Varela", role: "A", team: "monza" },
    { name: "Diego Adorante", role: "A", team: "venezia" },
    { name: "Dany Mota", role: "A", team: "monza" },
    { name: "Giovane", role: "A", team: "napoli" },
    { name: "Lorenzo Lucca", role: "A", team: "napoli" },
    { name: "Alieu Njie", role: "A", team: "fiorentina" },
    { name: "Daniel Birligea", role: "A", team: "frosinone" },
    { name: "Francesco Camarda", role: "A", team: "milan" },
    { name: "Alphadjo Cisse", role: "A", team: "milan" },
    { name: "Dominguez", role: "A", team: "sassuolo" },
    { name: "Matija Frigan", role: "A", team: "parma" },
    { name: "Havel", role: "A", team: "genoa" },
    { name: "Sandro Kulenovic", role: "A", team: "torino" },
    { name: "M'Bala Nzola", role: "A", team: "cagliari" },
    { name: "Exequiel Zeballos", role: "A", team: "monza" },
    { name: "Pontus Almqvist", role: "A", team: "parma" },
    { name: "Ekhator", role: "A", team: "juventus" },
    { name: "Gueye", role: "A", team: "udinese" },
    { name: "Noa Lang", role: "A", team: "napoli" },
    { name: "Lontani", role: "A", team: "parma" },
    { name: "Monteiro", role: "A", team: "lecce" },
    { name: "Cyril Ngonge", role: "A", team: "monza" },
    { name: "N'Dri", role: "A", team: "lecce" },
    { name: "Riccardo Sottil", role: "A", team: "fiorentina" },
    { name: "Keita Balde", role: "A", team: "monza" },
    { name: "Elphege", role: "A", team: "parma" },
    { name: "Seydou Fini", role: "A", team: "frosinone" },
    { name: "Jovanovic", role: "A", team: "udinese" },
    { name: "Touré", role: "A", team: "parma" },
    { name: "Zakaria Aboukhlal", role: "A", team: "torino" },
    { name: "Enem", role: "A", team: "bologna" },
    { name: "Fatah", role: "A", team: "lecce" },
    { name: "Fernandez", role: "A", team: "venezia" },
    { name: "Jesper Karlsson", role: "A", team: "bologna" },
    { name: "Mendy", role: "A", team: "cagliari" },
    { name: "De Souza Júnior", role: "A", team: "genoa" },
    { name: "Diallo Thiao", role: "A", team: "parma" },
    { name: "Arkadiusz Milik", role: "A", team: "juventus" },
    { name: "Vakoun Bayo", role: "A", team: "udinese" },
    { name: "Lisman", role: "A", team: "venezia" },
    { name: "Nicholas Pierini", role: "A", team: "sassuolo" },
    { name: "Skjellerup", role: "A", team: "sassuolo" },
    { name: "De Martis", role: "A", team: "parma" },
    { name: "Laerke", role: "A", team: "lecce" },
    { name: "Lauberbach", role: "A", team: "venezia" },
    { name: "Sugamele", role: "A", team: "cagliari" },
    { name: "Trepy", role: "A", team: "cagliari" },
    { name: "Vinciati", role: "A", team: "udinese" },
    { name: "David Pejicic", role: "A", team: "udinese" }
];
