const PLAYERS_DB = [
    { name: "Lautaro Martinez", role: "A", team: "inter" },
    { name: "Marcus Thuram", role: "A", team: "inter" },
    { name: "Nicolò Barella", role: "C", team: "inter" },
    { name: "Hakan Calhanoglu", role: "C", team: "inter" },
    { name: "Federico Dimarco", role: "D", team: "inter" },
    { name: "Yann Sommer", role: "P", team: "inter" },
    { name: "Rafael Leao", role: "A", team: "milan" },
    { name: "Christian Pulisic", role: "C", team: "milan" },
    { name: "Theo Hernandez", role: "D", team: "milan" },
    { name: "Mike Maignan", role: "P", team: "milan" },
    { name: "Dusan Vlahovic", role: "A", team: "juventus" },
    { name: "Kenan Yildiz", role: "A", team: "juventus" },
    { name: "Teun Koopmeiners", role: "C", team: "juventus" },
    { name: "Bremer", role: "D", team: "juventus" },
    { name: "Michele Di Gregorio", role: "P", team: "juventus" },
    { name: "Khvicha Kvaratskhelia", role: "A", team: "napoli" },
    { name: "Romelu Lukaku", role: "A", team: "napoli" },
    { name: "Scott McTominay", role: "C", team: "napoli" },
    { name: "Alessandro Buongiorno", role: "D", team: "napoli" },
    { name: "Alex Meret", role: "P", team: "napoli" },
    { name: "Paulo Dybala", role: "A", team: "roma" },
    { name: "Artem Dovbyk", role: "A", team: "roma" },
    { name: "Lorenzo Pellegrini", role: "C", team: "roma" },
    { name: "Gianluca Mancini", role: "D", team: "roma" },
    { name: "Mile Svilar", role: "P", team: "roma" },
    { name: "Ademola Lookman", role: "A", team: "atalanta" },
    { name: "Mateo Retegui", role: "A", team: "atalanta" },
    { name: "Ederson", role: "C", team: "atalanta" },
    { name: "Isak Hien", role: "D", team: "atalanta" },
    { name: "Marco Carnesecchi", role: "P", team: "atalanta" },
    { name: "Moise Kean", role: "A", team: "fiorentina" },
    { name: "Albert Gudmundsson", role: "A", team: "fiorentina" },
    { name: "David De Gea", role: "P", team: "fiorentina" },
    { name: "Taty Castellanos", role: "A", team: "lazio" },
    { name: "Mattia Zaccagni", role: "C", team: "lazio" },
    { name: "Ivan Provedel", role: "P", team: "lazio" }
];
